// Mock data for the Neutrals Portal prototype

const CASES = [
  {
    id: "NAM-2025-04812",
    title: "Atherton Holdings LLC v. Bridgewater Insurance Co.",
    type: "Commercial Arbitration",
    matter: "arb",
    status: "active",
    statusLabel: "Active",
    claimant: "Atherton Holdings LLC",
    respondent: "Bridgewater Insurance Co.",
    nextHearing: "May 14, 2026",
    nextHearingTime: "10:00 AM ET",
    format: "Zoom",
    location: "NAM New York",
    assignedAt: "Apr 21, 2026",
    amountInControversy: "$1,250,000",
    caseManager: "Maria Echeverria",
    tasksOpen: 2,
    docs: 14,
    pre: false,
  },
  {
    id: "NAM-2025-04501",
    title: "Delano v. Riverbend Medical Group",
    type: "Healthcare Malpractice — Mediation",
    matter: "med",
    status: "awaiting-decision",
    statusLabel: "Awaiting Payment",
    claimant: "Cassandra Delano",
    respondent: "Riverbend Medical Group",
    nextHearing: "—",
    nextHearingTime: "—",
    format: "—",
    location: "NAM Hicksville",
    assignedAt: "Mar 12, 2026",
    amountInControversy: "$420,000",
    caseManager: "James Park",
    tasksOpen: 0,
    docs: 22,
    pre: false,
  },
  {
    id: "NAM-2025-04733",
    title: "Quintero v. Greater Atlantic Mutual",
    type: "No-Fault Arbitration",
    matter: "arb",
    status: "active",
    statusLabel: "Active",
    claimant: "Luis Quintero",
    respondent: "Greater Atlantic Mutual",
    nextHearing: "May 12, 2026",
    nextHearingTime: "2:00 PM ET",
    format: "In-person",
    location: "NAM Garden City",
    assignedAt: "May 02, 2026",
    amountInControversy: "$78,500",
    caseManager: "Sandra Vasquez",
    tasksOpen: 1,
    docs: 9,
    pre: true,
  },
  {
    id: "NAM-2025-04199",
    title: "Westmark Capital Partners v. Heronridge LP",
    type: "Commercial Arbitration",
    matter: "arb",
    status: "active",
    statusLabel: "Pre-Hearing",
    claimant: "Westmark Capital Partners",
    respondent: "Heronridge LP",
    nextHearing: "May 19, 2026",
    nextHearingTime: "9:30 AM ET",
    format: "Zoom",
    location: "NAM New York",
    assignedAt: "Feb 28, 2026",
    amountInControversy: "$4,800,000",
    caseManager: "Maria Echeverria",
    tasksOpen: 1,
    docs: 47,
    pre: true,
  },
  {
    id: "NAM-2025-04388",
    title: "Okafor v. Sentinel Auto Insurance",
    type: "No-Fault Arbitration",
    matter: "arb",
    status: "active",
    statusLabel: "Active",
    claimant: "Adaeze Okafor",
    respondent: "Sentinel Auto Insurance",
    nextHearing: "May 22, 2026",
    nextHearingTime: "11:00 AM ET",
    format: "Zoom",
    location: "NAM Hicksville",
    assignedAt: "Apr 06, 2026",
    amountInControversy: "$45,200",
    caseManager: "James Park",
    tasksOpen: 0,
    docs: 6,
    pre: false,
  },
  {
    id: "NAM-2025-03991",
    title: "Petralia Family Trust v. Sea Cliff Estates",
    type: "Commercial Mediation",
    matter: "med",
    status: "closed",
    statusLabel: "Released",
    claimant: "Petralia Family Trust",
    respondent: "Sea Cliff Estates",
    nextHearing: "—",
    nextHearingTime: "—",
    format: "—",
    location: "NAM New York",
    assignedAt: "Jan 14, 2026",
    amountInControversy: "$680,000",
    caseManager: "Maria Echeverria",
    tasksOpen: 0,
    docs: 18,
    pre: false,
  },
];

const TASKS = [
  { id: "T-1041", title: "Submit timesheet for Atherton hearing", caseId: "NAM-2025-04812", type: "Timesheet", due: "Today", overdue: false, sla: "Due today by 5:00 PM", status: "open", icon: "clock" },
  { id: "T-1038", title: "Draft PMA for Delano v. Riverbend", caseId: "NAM-2025-04501", type: "PMA", due: "Overdue · 2d", overdue: true, sla: "Was due May 9", status: "open", icon: "file-edit" },
  { id: "T-1042", title: "Review pre-hearing materials", caseId: "NAM-2025-04733", type: "Review", due: "Tomorrow", overdue: false, sla: "Hearing May 12 · 2:00 PM ET", status: "open", icon: "folder" },
  { id: "T-1039", title: "Sign engagement agreement (DocuSign)", caseId: "NAM-2025-04199", type: "DocuSign", due: "May 13", overdue: false, sla: "Due in 2 days", status: "open", icon: "edit" },
  { id: "T-1043", title: "Respond to selection request", caseId: "NAM-2025-04901", type: "Selection", due: "May 16", overdue: false, sla: "Slate published May 10", status: "open", icon: "check-square" },
];

const HEARINGS = [
  { date: "12", month: "May", day: "Tue", caseId: "NAM-2025-04733", title: "Quintero v. Greater Atlantic Mutual", time: "2:00 PM ET", format: "In-person", location: "NAM Garden City — Room 3B" },
  { date: "14", month: "May", day: "Thu", caseId: "NAM-2025-04812", title: "Atherton Holdings LLC v. Bridgewater Insurance", time: "10:00 AM ET", format: "Zoom", location: "Zoom · ID 821 4490 7732" },
  { date: "19", month: "May", day: "Tue", caseId: "NAM-2025-04199", title: "Westmark Capital v. Heronridge LP", time: "9:30 AM ET", format: "Zoom", location: "Zoom (pre-hearing conf.)" },
  { date: "22", month: "May", day: "Fri", caseId: "NAM-2025-04388", title: "Okafor v. Sentinel Auto Insurance", time: "11:00 AM ET", format: "Zoom", location: "Zoom · ID 736 1198 4490" },
];

const NOTIFICATIONS = [
  { id: "N-204", title: "New case assigned", desc: "NAM-2025-04901 · Hartley v. Coastal Mutual — Arbitration selection slate", time: "12 min ago", unread: true, type: "case" },
  { id: "N-203", title: "Hearing time updated", desc: "NAM-2025-04812 · Atherton — moved to 10:00 AM ET May 14", time: "1 hr ago", unread: true, type: "hearing" },
  { id: "N-202", title: "Document added", desc: "NAM-2025-04733 · Pre-hearing brief uploaded by claimant counsel", time: "3 hr ago", unread: true, type: "doc" },
  { id: "N-201", title: "Timesheet approved", desc: "NAM-2025-04501 · Mediation session Apr 28 — payment scheduled May 15", time: "Yesterday", unread: false, type: "payment" },
  { id: "N-200", title: "PMA released", desc: "NAM-2025-03991 · Petralia Family Trust v. Sea Cliff Estates", time: "Yesterday", unread: false, type: "pma" },
  { id: "N-199", title: "Vacation approved", desc: "Jun 22 – Jun 28 vacation approved by NAM Scheduling", time: "2 days ago", unread: false, type: "availability" },
  { id: "N-198", title: "DocuSign envelope received", desc: "NAM-2025-04199 · Engagement agreement awaiting your signature", time: "3 days ago", unread: false, type: "doc" },
];

const TIMESHEETS = [
  { id: "TS-2026-0481", caseId: "NAM-2025-04501", date: "Apr 28, 2026", hours: "3.5", status: "approved", statusLabel: "Payment scheduled", paymentDate: "May 15, 2026", amount: "$1,575.00" },
  { id: "TS-2026-0467", caseId: "NAM-2025-04199", date: "Apr 21, 2026", hours: "2.0", status: "approved", statusLabel: "Paid", paymentDate: "May 01, 2026", amount: "$900.00" },
  { id: "TS-2026-0455", caseId: "NAM-2025-04812", date: "Apr 14, 2026", hours: "4.0", status: "review", statusLabel: "Under Review", paymentDate: "—", amount: "$1,800.00" },
  { id: "TS-2026-0441", caseId: "NAM-2025-04388", date: "Apr 02, 2026", hours: "1.5", status: "approved", statusLabel: "Paid", paymentDate: "Apr 16, 2026", amount: "$675.00" },
];

const DOCUMENTS = [
  { name: "Statement of Claim — Atherton.pdf", type: "pdf", size: "2.1 MB", uploaded: "Apr 22, 2026", by: "Claimant counsel", folder: "Submitting Party" },
  { name: "Answer & Counterclaim.pdf", type: "pdf", size: "1.8 MB", uploaded: "Apr 28, 2026", by: "Respondent counsel", folder: "Opposing Party" },
  { name: "Exhibit A — Contract (signed).pdf", type: "pdf", size: "850 KB", uploaded: "Apr 22, 2026", by: "Claimant counsel", folder: "Submitting Party" },
  { name: "Pre-hearing brief — Bridgewater.docx", type: "doc", size: "240 KB", uploaded: "May 06, 2026", by: "Respondent counsel", folder: "Opposing Party" },
  { name: "Witness list.pdf", type: "pdf", size: "120 KB", uploaded: "May 07, 2026", by: "Claimant counsel", folder: "Submitting Party" },
  { name: "Hearing notes (private).docx", type: "doc", size: "32 KB", uploaded: "May 09, 2026", by: "You", folder: "Neutral" },
  { name: "Engagement agreement (countersigned).pdf", type: "pdf", size: "180 KB", uploaded: "Apr 23, 2026", by: "NAM", folder: "Neutral" },
];

const CLAUSES = [
  { id: "c1", name: "Mutual general release", selected: true, desc: "Standard mutual release of all claims arising from the matter." },
  { id: "c2", name: "Confidentiality of terms", selected: true, desc: "Settlement terms confidential except as required by law or tax authorities." },
  { id: "c3", name: "Payment schedule — lump sum", selected: true, desc: "Single payment within 30 days of execution." },
  { id: "c4", name: "Payment schedule — structured", selected: false, desc: "Installments over a defined period." },
  { id: "c5", name: "Non-disparagement (mutual)", selected: false, desc: "Mutual non-disparagement covering oral and written statements." },
  { id: "c6", name: "Indemnification (medical liens)", selected: false, desc: "Claimant indemnifies for outstanding Medicare/Medicaid liens." },
  { id: "c7", name: "Tax allocation (1099 reporting)", selected: false, desc: "Allocation between physical and emotional damages for tax reporting." },
  { id: "c8", name: "Court enforcement reservation", selected: true, desc: "Reserve jurisdiction in NAM for enforcement." },
];

window.NPDATA = { CASES, TASKS, HEARINGS, NOTIFICATIONS, TIMESHEETS, DOCUMENTS, CLAUSES };
